import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '欢迎',
    },
    {
      type: 'category',
      label: '开始使用',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/learning-path',
        'getting-started/updating',
        'getting-started/nix-setup',
      ],
    },
    {
      type: 'category',
      label: '用户指南',
      items: [
        'user-guide/configuration',
        'user-guide/cli',
        'user-guide/docker',
        'user-guide/git-worktrees',
        'user-guide/checkpoints-and-rollback',
        'user-guide/profiles',
        'user-guide/sessions',
        'user-guide/security',
        {
          type: 'category',
          label: '功能',
          items: [
            'user-guide/features/overview',
            'user-guide/features/skills',
            'user-guide/features/memory',
            'user-guide/features/mcp',
            'user-guide/features/tools',
            'user-guide/features/provider-routing',
            'user-guide/features/credential-pools',
            'user-guide/features/delegation',
            'user-guide/features/cron',
            'user-guide/features/hooks',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/acp',
            'user-guide/features/batch-processing',
            'user-guide/features/api-server',
            'user-guide/features/browser',
            'user-guide/features/code-execution',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/fallback-providers',
            'user-guide/features/honcho',
            'user-guide/features/image-generation',
            'user-guide/features/memory-providers',
            'user-guide/features/plugins',
            'user-guide/features/rl-training',
            'user-guide/features/tts',
            'user-guide/features/voice-mode',
            'user-guide/features/vision',
          ],
        },
        {
          type: 'category',
          label: '消息网关',
          items: [
            'user-guide/messaging/index',
            'user-guide/messaging/discord',
            'user-guide/messaging/telegram',
            'user-guide/messaging/dingtalk',
            'user-guide/messaging/feishu',
            'user-guide/messaging/email',
            'user-guide/messaging/matrix',
            'user-guide/messaging/mattermost',
            'user-guide/messaging/homeassistant',
            'user-guide/messaging/open-webui',
            'user-guide/messaging/signal',
            'user-guide/messaging/slack',
            'user-guide/messaging/sms',
            'user-guide/messaging/webhooks',
            'user-guide/messaging/wecom',
            'user-guide/messaging/whatsapp',
          ],
        },
        {
          type: 'category',
          label: '技能',
          items: [
            'user-guide/skills/godmode',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '开发者指南',
      items: [
        'developer-guide/architecture',
        'developer-guide/agent-loop',
        'developer-guide/contributing',
        'developer-guide/environments',
        'developer-guide/creating-skills',
        'developer-guide/adding-tools',
        'developer-guide/adding-providers',
        'developer-guide/tools-runtime',
        'developer-guide/provider-runtime',
        'developer-guide/prompt-assembly',
        'developer-guide/context-compression-and-caching',
        'developer-guide/memory-provider-plugin',
        'developer-guide/session-storage',
        'developer-guide/cron-internals',
        'developer-guide/gateway-internals',
        'developer-guide/acp-internals',
        'developer-guide/extending-the-cli',
        'developer-guide/trajectory-format',
      ],
    },
    {
      type: 'category',
      label: '集成',
      items: [
        'integrations/index',
        'integrations/providers',
      ],
    },
    {
      type: 'category',
      label: '参考',
      items: [
        'reference/cli-commands',
        'reference/profile-commands',
        'reference/slash-commands',
        'reference/environment-variables',
        'reference/skills-catalog',
        'reference/optional-skills-catalog',
        'reference/mcp-config-reference',
        'reference/tools-reference',
        'reference/toolsets-reference',
        'reference/faq',
      ],
    },
    {
      type: 'category',
      label: '指南',
      items: [
        'guides/automate-with-cron',
        'guides/build-a-hermes-plugin',
        'guides/daily-briefing-bot',
        'guides/delegation-patterns',
        'guides/local-llm-on-mac',
        'guides/migrate-from-openclaw',
        'guides/python-library',
        'guides/team-telegram-assistant',
        'guides/tips',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/work-with-skills',
      ],
    },
  ],
};

export default sidebars;
